services:
  - type: web
    name: vision-api-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcp-key.json
    autoDeploy: true
    secretFiles:
      - name: gcp-key.json
        path: /etc/secrets/gcp-key.json
